CC=c++
CFLAGS=-I.

Assignment3: basicAcceptanceTest.cpp insertionsort.cpp mergesort.cpp radixsort.cpp heapsort.cpp
	$(CC) -Wall -g basicAcceptanceTest.cpp insertionsort.cpp mergesort.cpp radixsort.cpp heapsort.cpp -o assignment3

clean:
	rm assignment3
